<?php
require_once __DIR__.'/layout.php';
require_once __DIR__.'/depo-cikis-lib.php';
require_login();
if(!can_access_warehouse_dispatch()){flash('error','Depo çıkış bölümüne erişim yetkiniz yok.');redirect('dashboard.php');}
depo_cikis_db_ensure();
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf(); $action=(string)($_POST['action']??''); $id=(int)($_POST['id']??0);
    try{
        if($action==='save'){$id=depo_cikis_save($id);flash('success','Depo çıkış fişi kaydedildi.');redirect('depo-cikis.php?edit='.$id);}
        if($action==='processed'){depo_cikis_mark_processed($id);flash('success','Fiş işlendi olarak işaretlendi.');}
        if($action==='post_cari'){$mid=depo_cikis_post_to_cari($id);flash('success','Fiş cariye işlendi ve işlendi olarak işaretlendi. Hareket #'.$mid);}
    }catch(Throwable $e){flash('error',$e->getMessage());}
    redirect('depo-cikis.php'.($id>0?'?edit='.$id:''));
}
$editId=(int)($_GET['edit']??0);$edit=$editId?depo_cikis_load($editId):null;
if($edit && !depo_cikis_can_edit($edit) && is_warehouse_dispatch_operator()){$edit=null;flash('error','Bu fişi düzenleme yetkiniz yok.');}
$cariler=db()->query('SELECT id,name,city,address FROM cariler ORDER BY name')->fetchAll();
$productRows=teklif_products_for_select();
$productJson=json_encode(array_map(function($p){return [
    'barcode'=>(string)($p['barcode']??''),
    'name'=>(string)($p['name']??''),
    'product_type'=>(string)($p['product_type']??''),
    'default_unit_price'=>(float)($p['default_unit_price']??0),
];},$productRows),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
$listSql='SELECT w.*,u.display_name AS creator_name FROM warehouse_dispatches w LEFT JOIN users u ON u.id=w.created_by';$params=[];
if(is_warehouse_user()){$listSql.=' WHERE w.created_by=?';$params[]=(int)(current_user()['id']??0);}$listSql.=' ORDER BY w.dispatch_date DESC,w.id DESC LIMIT 150';
$s=db()->prepare($listSql);$s->execute($params);$list=$s->fetchAll();$items=$edit['items']??[];$rows=max(6,count($items)+2);
$cariJson=json_encode($cariler,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
page_header('Depo Çıkış','depo_cikis');
?>
<style>
.wd{display:grid;gap:16px;max-width:1500px;margin:auto}.wd-hero{padding:20px 22px;border-radius:22px;background:linear-gradient(135deg,#102818,#23613c);color:#fff}.wd-hero h2{margin:4px 0}.wd-hero p{margin:0;color:#e4f0e8}.wd-card{padding:18px;border:1px solid #e5dccf;border-radius:20px;background:#fff}.wd-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.wd-grid label{display:grid;gap:5px;font-size:12px;font-weight:850}.wd-grid .wide{grid-column:span 2}.wd-grid input,.wd-grid select,.wd-grid textarea{width:100%;min-height:42px;padding:9px;border:1px solid #ddd2c1;border-radius:11px}.wd-table{overflow:auto;margin-top:15px;border:1px solid #e5dccf;border-radius:14px}.wd table{width:100%;border-collapse:collapse;min-width:900px}.wd th{padding:10px;background:#16482e;color:#fff;text-align:left;font-size:11px}.wd td{padding:8px;border-bottom:1px solid #eee5d9;vertical-align:top}.wd-table input{width:100%;min-height:38px;padding:7px;border:1px solid #ddd2c1;border-radius:9px}.wd-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.wd-actions a,.wd-actions button{display:inline-flex;align-items:center;border:1px solid #d9cfbf;border-radius:999px;padding:8px 12px;background:#fff;color:#173f29;font-weight:850;text-decoration:none;cursor:pointer}.wd-actions .primary{background:#16482e;color:#fff}.wd-actions form{display:inline}.status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:900;background:#fff2d8;color:#885f0b}.status.done{background:#e7f6eb;color:#216b39}.wd-total{text-align:right;margin-top:12px;font-size:21px;color:#173f29}.muted{color:#776f64}.wd-product-help{display:block;margin-top:8px;color:#776f64;font-size:11px;font-weight:700}@media(max-width:800px){.wd-grid{grid-template-columns:1fr 1fr}.wd-grid .wide{grid-column:1/-1}}@media(max-width:520px){.wd-grid{grid-template-columns:1fr}.wd-grid .wide{grid-column:1}.wd-card{padding:12px}.wd-hero{padding:17px}}
</style>
<div class="wd" style="display:grid!important">
 <section class="wd-hero"><small>MAĞAZA / DEPO ÇIKIŞ</small><h2>Sipariş fişi hazırla</h2><p>Depodan çıkan ürünleri kaydet, düzenle ve yazdır.</p></section>
 <section class="wd-card">
  <h3><?php echo $edit?'Fişi düzenle':'Yeni depo çıkış fişi'; ?></h3>
  <form method="post" id="wdForm"><?php echo csrf_field(); ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?php echo e($edit['id']??0); ?>">
   <div class="wd-grid">
    <label>Fiş başlığı<input value="SİPARİŞ FİŞİ" disabled></label><label>Fiş no<input name="dispatch_no" required value="<?php echo e($edit['dispatch_no']??depo_cikis_next_no()); ?>"></label><label>Tarih<input type="date" name="dispatch_date" required value="<?php echo e($edit['dispatch_date']??date('Y-m-d')); ?>"></label>
    <label class="wide">Cari<select name="cari_id" id="wdCari"><option value="">Cari seçmeden elle yaz</option><?php foreach($cariler as $c): ?><option value="<?php echo e($c['id']); ?>" <?php echo (int)($edit['cari_id']??0)===(int)$c['id']?'selected':''; ?>><?php echo e($c['name']); ?></option><?php endforeach; ?></select></label>
    <label class="wide">Firma / Müşteri<input name="customer_name" id="wdCustomer" required value="<?php echo e($edit['customer_name']??''); ?>"></label><label class="wide">Şehir<input name="customer_city" id="wdCity" value="<?php echo e($edit['customer_city']??''); ?>"></label><label class="wide">Adres<textarea name="customer_address" id="wdAddress"><?php echo e($edit['customer_address']??''); ?></textarea></label><label class="wide">Not<textarea name="note"><?php echo e($edit['note']??''); ?></textarea></label>
   </div>
   <datalist id="wdProductOptions"><?php foreach($productRows as $p): ?><option value="<?php echo e($p['name']); ?>"<?php if(trim((string)($p['barcode']??''))!==''): ?> label="<?php echo e((string)$p['barcode'].(trim((string)($p['product_type']??''))!==''?' · '.(string)$p['product_type']:'')); ?>"<?php endif; ?>></option><?php endforeach; ?></datalist>
   <small class="wd-product-help">Ürün adını yazmaya başlayınca Sipariş Ver bölümünde kayıtlı ürünler hatırlatma olarak çıkar. Örn: 6000 → 6000 BİTKE ERKEK MODAL ÇORAP.</small>
   <div class="wd-table"><table id="wdRows"><thead><tr><th>Barkod</th><th>Ürün adı</th><th>Açıklama</th><th>Miktar</th><th>Birim fiyat</th><th>Tutar</th><th></th></tr></thead><tbody><?php for($i=0;$i<$rows;$i++): ?><tr><td><input name="product_barcode[]" class="product-barcode" value="<?php echo e($items[$i]['product_barcode']??''); ?>"></td><td><input name="product_name[]" list="wdProductOptions" class="product-name" autocomplete="off" value="<?php echo e($items[$i]['product_name']??''); ?>"></td><td><input name="product_type[]" class="product-type" value="<?php echo e($items[$i]['product_type']??''); ?>"></td><td><input class="calc qty" name="quantity[]" inputmode="decimal" value="<?php echo e($items[$i]['quantity']??''); ?>"></td><td><input class="calc price" name="unit_price[]" inputmode="decimal" value="<?php echo e($items[$i]['unit_price']??''); ?>"></td><td class="line">0,00</td><td><button type="button" class="remove">×</button></td></tr><?php endfor; ?></tbody></table></div>
   <div class="wd-total">Toplam: <strong id="wdTotal">0,00 TL</strong></div><div class="wd-actions"><button class="primary">Kaydet</button><button type="button" id="wdAdd">Satır ekle</button><?php if($edit): ?><a target="_blank" href="depo-cikis-yazdir.php?id=<?php echo e($edit['id']); ?>">PDF / Yazdır</a><a href="depo-cikis.php">Yeni fiş</a><?php endif; ?></div>
  </form>
 </section>
 <section class="wd-card"><h3>Kayıtlı depo çıkışları</h3><div class="wd-table"><table><thead><tr><th>Tarih / No</th><th>Firma</th><th>Toplam</th><th>Durum</th><th>Oluşturan</th><th>İşlemler</th></tr></thead><tbody><?php if(!$list): ?><tr><td colspan="6">Henüz kayıt yok.</td></tr><?php endif; ?><?php foreach($list as $r): ?><tr><td><?php echo e(tr_date($r['dispatch_date'])); ?><br><small>#<?php echo e($r['dispatch_no']); ?></small></td><td><?php echo e($r['customer_name']); ?></td><td><?php echo e(money((float)$r['total'])); ?></td><td><span class="status <?php echo (int)$r['processed']?'done':''; ?>"><?php echo (int)$r['posted_to_cari']?'Cariye işlendi':((int)$r['processed']?'İşlendi':'Bekliyor'); ?></span></td><td><?php echo e($r['creator_name']?:'-'); ?></td><td><div class="wd-actions"><?php if(depo_cikis_can_edit($r)): ?><a href="depo-cikis.php?edit=<?php echo e($r['id']); ?>">Düzenle</a><?php endif; ?><a target="_blank" href="depo-cikis-yazdir.php?id=<?php echo e($r['id']); ?>">Yazdır</a><?php if(can_process_warehouse_dispatch()): ?><?php if(!(int)$r['processed']): ?><form method="post"><?php echo csrf_field(); ?><input type="hidden" name="action" value="processed"><input type="hidden" name="id" value="<?php echo e($r['id']); ?>"><button>İşlendi</button></form><?php endif; ?><form method="post" onsubmit="return confirm('Bu fiş cariye işlensin mi?');"><?php echo csrf_field(); ?><input type="hidden" name="action" value="post_cari"><input type="hidden" name="id" value="<?php echo e($r['id']); ?>"><button><?php echo (int)$r['posted_to_cari']?'Cariyi Güncelle':'Cariye İşle'; ?></button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<script>(function(){const cariler=<?php echo $cariJson?:'[]'; ?>,products=<?php echo $productJson?:'[]'; ?>,sel=document.querySelector('#wdCari');sel?.addEventListener('change',()=>{const c=cariler.find(x=>String(x.id)===sel.value);if(!c)return;document.querySelector('#wdCustomer').value=c.name||'';document.querySelector('#wdCity').value=c.city||'';document.querySelector('#wdAddress').value=c.address||''});const body=document.querySelector('#wdRows tbody'),fmt=new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});function num(v){v=String(v||'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');return parseFloat(v)||0}function norm(v){return String(v||'').trim().toLocaleUpperCase('tr-TR')}function calc(){let sum=0;body.querySelectorAll('tr').forEach(r=>{const n=num(r.querySelector('.qty').value)*num(r.querySelector('.price').value);sum+=n;r.querySelector('.line').textContent=fmt.format(n)});document.querySelector('#wdTotal').textContent=fmt.format(sum)+' TL'}function applyProduct(row,source){if(!row)return;const name=row.querySelector('.product-name'),barcode=row.querySelector('.product-barcode'),type=row.querySelector('.product-type'),price=row.querySelector('.price');let p=null;if(source==='barcode'&&barcode?.value){p=products.find(x=>String(x.barcode||'').trim()===String(barcode.value||'').trim())||null}if(!p&&name?.value){const wanted=norm(name.value);p=products.find(x=>norm(x.name)===wanted)||null}if(!p)return;if(name&&!name.value)name.value=p.name||'';if(barcode&&p.barcode)barcode.value=p.barcode;if(type&&p.product_type)type.value=p.product_type;if(price&&!price.value&&Number(p.default_unit_price||0)>0)price.value=String(p.default_unit_price).replace('.',',');calc()}body.addEventListener('input',e=>{if(e.target.classList.contains('calc'))calc()});body.addEventListener('change',e=>{if(e.target.classList.contains('product-name'))applyProduct(e.target.closest('tr'),'name');if(e.target.classList.contains('product-barcode'))applyProduct(e.target.closest('tr'),'barcode')});body.addEventListener('click',e=>{if(e.target.classList.contains('remove')){e.target.closest('tr').remove();calc()}});document.querySelector('#wdAdd').addEventListener('click',()=>{const r=body.rows[0].cloneNode(true);r.querySelectorAll('input').forEach(i=>i.value='');r.querySelector('.line').textContent='0,00';body.appendChild(r)});calc()})();</script>
<?php page_footer(); ?>
