<?php
require_once __DIR__ . '/teklif-db.php';
require_login();

$offerId = (int)($_GET['id'] ?? 0);
$offer = teklif_load($offerId);
if (!$offer) {
    flash('error', 'PDF alınacak teklif bulunamadı.');
    redirect('teklif-ver.php');
}

$title = $offer['document_title'] ?: 'SİPARİŞ FİŞİ';
$offerNo = $offer['offer_no'] ?: '';
$offerDate = $offer['offer_date'] ?: date('Y-m-d');
$customer = $offer['customer_name'] ?: '';
$city = $offer['customer_city'] ?: '';
$currency = $offer['currency'] ?: 'TL';
$quantityLabel = $offer['quantity_label'] ?: 'DZ';
$note = $offer['note'] ?: '';
$footerText = $offer['footer_text'] ?: 'MALIMIZDAN HAYIR GÖRÜN.';
$termText = $offer['term_text'] ?: '';
$subtotal = (float)($offer['subtotal'] ?? 0);
$vatEnabled = (int)($offer['vat_enabled'] ?? 0) === 1;
$vatRate = (float)($offer['vat_rate'] ?? 10);
$vatAmount = (float)($offer['vat_amount'] ?? 0);
$grandTotal = (float)($offer['grand_total'] ?? ($subtotal + $vatAmount));
$rows = $offer['items'] ?? [];
while (count($rows) < 13) {
    $rows[] = ['product_name'=>'', 'product_type'=>'', 'quantity'=>0, 'unit_price'=>0, 'line_total'=>0];
}
$docTypeLabel = (mb_stripos($title, 'SİPARİŞ') !== false || mb_stripos($title, 'SIPARIS') !== false) ? 'SİPARİŞ' : 'TEKLİF';
$logoSrc = 'assets/dumanlar-logo-arkaplansiz.png?v=20';
?>
<!doctype html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo e($title); ?> - <?php echo e($customer); ?></title>
<style>
*{box-sizing:border-box} :root{--navy:#061a33;--gold:#c49a4f;--gold2:#efd28a;--line:#e6dfd2;--cream:#faf4e8;--ink:#071a33} html,body{margin:0;padding:0;background:#dfe3e7;font-family:Arial,Helvetica,sans-serif;color:var(--ink)}
.toolbar{position:sticky;top:0;z-index:30;display:flex;gap:10px;justify-content:center;padding:12px;background:var(--navy)} .toolbar button,.toolbar a{border:0;border-radius:999px;padding:10px 16px;background:#fff;color:var(--navy);font-weight:800;text-decoration:none;cursor:pointer}
.page{width:210mm;height:297mm;margin:14px auto;background:#fff;box-shadow:0 10px 28px rgba(0,0,0,.20);position:relative;overflow:hidden;border:1px solid #d7dce2}
.header{height:58mm;padding:7mm 10mm 0;background:linear-gradient(180deg,#fff 0,#fff 80%,#fbf7ef 100%);border-top:3mm solid var(--navy);position:relative;text-align:center;overflow:hidden}.header:before{content:'';position:absolute;left:11mm;right:11mm;bottom:0;height:1px;background:linear-gradient(90deg,transparent,var(--gold),transparent)}.header:after{content:'';position:absolute;left:50%;bottom:0;width:2.3mm;height:2.3mm;background:var(--gold);transform:translate(-50%,50%) rotate(45deg)}.logo{display:block;width:118mm;height:34mm;object-fit:contain;margin:0 auto 4mm}.brand-line{display:flex;align-items:center;justify-content:center;gap:7mm;color:var(--gold);font-size:2.7mm;letter-spacing:.8mm;font-weight:800;text-transform:uppercase}.brand-line:before,.brand-line:after{content:'';width:30mm;height:.35mm;background:linear-gradient(90deg,transparent,var(--gold),transparent)}
.contact{height:11mm;display:grid;grid-template-columns:34mm 47mm 34mm 34mm 1fr;align-items:center;border-top:.45mm solid var(--gold);border-bottom:.45mm solid var(--gold);background:#fff;font-size:2.45mm;color:#0e1d31;font-weight:800}.contact div{height:100%;display:flex;align-items:center;justify-content:center;gap:1.4mm;border-right:1px solid #d8dee5;padding:0 1.8mm;text-align:center;overflow:hidden;white-space:nowrap}.contact div:last-child{border-right:0;font-size:2mm;white-space:normal;line-height:1.14}.ico{width:5.2mm;height:5.2mm;border:1px solid var(--gold);border-radius:50%;display:inline-flex;align-items:center;justify-content:center;color:var(--gold);font-size:2.45mm;flex:0 0 auto}.whatsapp-ico{border-color:#25d366;color:#25d366}.whatsapp-ico svg{width:3.35mm;height:3.35mm;display:block;fill:currentColor}
.content{padding:8.5mm 10mm 44mm;position:relative}.doc-head{display:grid;grid-template-columns:1fr 70mm;gap:12mm;align-items:start;margin-bottom:7mm}.title-wrap h1{font-family:Georgia,'Times New Roman',serif;font-size:17.2mm;letter-spacing:.9mm;line-height:.95;margin:0;color:var(--navy);font-weight:700}.title-rule{display:flex;align-items:center;gap:4mm;width:82mm;margin:4.8mm 0 4.2mm}.title-rule:before,.title-rule:after{content:'';height:.35mm;background:linear-gradient(90deg,transparent,var(--gold),transparent);flex:1}.title-rule span{width:2mm;height:2mm;background:var(--gold);transform:rotate(45deg)}.customer-name{font-size:4mm;font-weight:800;color:#273249;margin-bottom:6mm;max-width:112mm;text-transform:uppercase}.city{font-size:4mm;font-weight:800;color:#273249}.city:before{content:' ';display:inline-block;width:4.5mm;height:4.5mm;border-radius:50%;background:var(--gold);margin-right:2.5mm;vertical-align:-.8mm}
.date-box{border:1.25px solid var(--navy);border-radius:2mm;background:#fff;box-shadow:0 5px 13px rgba(12,28,52,.04);overflow:hidden;margin-top:1.5mm}.date-row{display:grid;grid-template-columns:28mm 1fr;align-items:center;min-height:11.8mm;border-bottom:1px solid #d8dee5}.date-row:last-child{border-bottom:0}.date-row b{height:100%;display:flex;align-items:center;padding:0 4mm;border-right:1px solid #aab4c1;font-size:3mm;color:var(--navy);font-weight:900}.date-row strong{padding:0 5mm;font-size:3.25mm;color:#24324a;text-align:right;font-weight:900}
table.items{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:3.05mm;border:1px solid var(--gold);border-radius:2mm;overflow:hidden}.items th{background:var(--navy);color:var(--gold2);text-align:center;padding:2.35mm 1.8mm;border-right:1px solid var(--gold);font-weight:900}.items th:last-child{border-right:0}.items thead tr.sub th{background:var(--cream);color:#1c2b42;padding:1.75mm 1.8mm;font-size:2.65mm;border-bottom:1px solid var(--line)}.items td{height:5mm;border-bottom:1px solid var(--line);border-right:1px solid var(--line);padding:1mm 2mm;color:#263246;font-weight:700}.items td:last-child{border-right:0}.items td:nth-child(2),.items td:nth-child(3),.items td:nth-child(4){text-align:center}.items td.right{text-align:right}.items small{display:block;margin-top:.2mm;color:#667085;font-size:2.1mm;font-weight:600}.items .empty{color:transparent}.total-line td{height:6.2mm;background:#fff}.total-line .label{background:var(--navy);color:var(--gold2);text-align:center;font-weight:900}.total-line .amount{color:#9a702a;font-weight:900;text-align:center;font-size:3.2mm;background:#fbf5e9}
.note{display:flex;align-items:center;gap:3mm;margin:5mm 2.5mm 0;font-size:3.25mm;color:#273249;font-weight:800}.note-mark{width:8mm;height:8mm;border-radius:50%;background:var(--navy);color:var(--gold2);display:inline-flex;align-items:center;justify-content:center;font-size:3mm;flex:0 0 auto}.note-text{flex:1;border-bottom:1px dotted #aab4c1;min-height:5mm;padding-top:1.2mm;font-weight:700;color:#333}.term{margin:2.7mm 2.5mm 0;font-size:2.7mm;color:#4b5563;font-weight:600}
.bottom{position:absolute;left:0;right:0;bottom:0;height:41mm;overflow:hidden;background:linear-gradient(to bottom,var(--navy) 0,var(--navy) 33mm,#efc36d 33mm,#f9e4aa 37mm,#efc36d 41mm);border-top:1mm solid var(--gold)}.bottom:after{content:attr(data-footer);position:absolute;left:0;right:0;bottom:0;height:8mm;display:flex;align-items:center;justify-content:center;font-family:Georgia,serif;font-size:3.4mm;letter-spacing:.65mm;color:#513910;z-index:5;white-space:nowrap}.features{position:absolute;left:0;right:0;top:0;height:33mm;display:grid;grid-template-columns:1fr 1fr 1fr 54mm;align-items:center;gap:3mm;padding:4.6mm 10.5mm;color:#fff;overflow:hidden}.feature{display:grid;grid-template-columns:9mm 1fr;gap:2.4mm;align-items:center;border-right:1px solid rgba(196,154,79,.65);height:20mm;padding-right:2.4mm}.feature:nth-child(3){border-right:0}.ficon{width:8.8mm;height:8.8mm;border:1.2px solid var(--gold);border-radius:50%;display:flex;align-items:center;justify-content:center;color:var(--gold);font-size:3mm}.feature b{display:block;color:var(--gold2);font-size:2.55mm;margin-bottom:.6mm}.feature span{display:block;font-size:2.05mm;line-height:1.2;color:#e7edf5}.thanks{border:1.1px solid var(--gold);border-radius:2mm;padding:4.5mm;text-align:center;color:var(--gold2);font-family:Georgia,serif;font-size:3.9mm;line-height:1.2;font-style:italic}
@page{size:A4;margin:0}@media print{html,body{width:210mm!important;height:auto!important;background:#fff!important;overflow:hidden!important;margin:0!important;padding:0!important}.toolbar{display:none!important}.page{margin:0 auto!important;border:0!important;box-shadow:none!important;width:209mm!important;height:286mm!important;overflow:hidden!important}.header{height:49mm!important;padding-top:5mm!important;border-top-width:2.4mm!important}.logo{width:111mm!important;height:30mm!important;margin-bottom:2.5mm!important}.brand-line{font-size:2.35mm!important}.contact{height:9.5mm!important;font-size:2.22mm!important;grid-template-columns:32mm 44mm 32mm 33mm 1fr!important}.contact div{gap:1mm!important;padding:0 1.4mm!important}.contact div:last-child{font-size:1.86mm!important}.ico{width:4.5mm!important;height:4.5mm!important;font-size:2.1mm!important}.whatsapp-ico svg{width:2.95mm!important;height:2.95mm!important}.content{padding:7mm 9.5mm 39mm!important}.doc-head{margin-bottom:5mm!important;gap:10mm!important}.title-wrap h1{font-size:15.6mm!important}.title-rule{margin:3.8mm 0 3.4mm!important}.customer-name{margin-bottom:5mm!important}.city{font-size:3.6mm!important}.date-row{min-height:10mm!important}.date-row b{font-size:2.65mm!important}.date-row strong{font-size:2.8mm!important}.items th{padding:1.9mm 1.5mm!important}.items thead tr.sub th{padding:1.35mm 1.5mm!important}.items td{height:4.45mm!important;padding:.85mm 1.7mm!important}.total-line td{height:5.25mm!important}.note{margin-top:3.2mm!important;font-size:2.9mm!important}.bottom{height:37mm!important;background:linear-gradient(to bottom,var(--navy) 0,var(--navy) 29.7mm,#efc36d 29.7mm,#f9e4aa 33.3mm,#efc36d 37mm)!important}.bottom:after{height:7.2mm!important;font-size:3mm!important}.features{height:29.7mm!important;padding:3.8mm 9mm!important;grid-template-columns:1fr 1fr 1fr 51mm!important}.feature{grid-template-columns:8.5mm 1fr!important;gap:2mm!important;height:18mm!important}.ficon{width:8.2mm!important;height:8.2mm!important;font-size:2.8mm!important}.feature b{font-size:2.3mm!important}.feature span{font-size:1.95mm!important}.thanks{font-size:3.35mm!important;padding:3.4mm!important}.header,.contact,.bottom,.features,.items th,.total-line .label{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style>
</head>
<body>
<div class="toolbar"><button onclick="window.print()">Yazdır / PDF al</button><a href="teklif-ver.php?edit=<?php echo e($offerId); ?>">Düzenlemeye dön</a><a href="teklif-ver.php">Teklif listesi</a></div>
<main class="page">
<section class="header"><img class="logo" src="<?php echo e($logoSrc); ?>" alt="Dumanlar"><div class="brand-line">ÇORAP & TEKSTİL ÜRETİMİ</div></section>
<section class="contact"><div><span class="ico">T</span>+90 356 715 82 83</div><div><span class="ico">M</span>dumanlartekstil@yahoo.com</div><div><span class="ico">W</span>dumanlartekstil.com.tr</div><div><span class="ico whatsapp-ico" aria-label="WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16.02 3.2A12.73 12.73 0 0 0 5.2 22.65L3.8 28.8l6.29-1.66A12.74 12.74 0 1 0 16.02 3.2Zm0 23.12c-2.05 0-4.06-.6-5.78-1.74l-.41-.27-3.74.99 1-3.64-.27-.42a10.35 10.35 0 1 1 9.2 5.08Zm5.96-7.74c-.33-.16-1.93-.95-2.23-1.06-.3-.11-.52-.16-.74.16-.22.33-.85 1.06-1.04 1.28-.19.22-.38.25-.7.08-.33-.16-1.38-.51-2.63-1.62-.97-.86-1.62-1.92-1.81-2.25-.19-.33-.02-.5.14-.66.15-.15.33-.38.49-.57.16-.19.22-.33.33-.55.11-.22.05-.41-.03-.57-.08-.16-.74-1.78-1.01-2.44-.27-.64-.54-.55-.74-.56h-.63c-.22 0-.57.08-.87.41-.3.33-1.14 1.11-1.14 2.71s1.17 3.15 1.33 3.37c.16.22 2.3 3.51 5.57 4.92.78.34 1.39.54 1.86.69.78.25 1.49.21 2.05.13.63-.09 1.93-.79 2.2-1.55.27-.76.27-1.42.19-1.55-.08-.14-.3-.22-.63-.38Z"/></svg></span>0(356)715 82 83</div><div><span class="ico">A</span>Kelkit Usb Mah. Beyllikbükü Cad. No:8 ERBAA/TOKAT</div></section>
<section class="content"><div class="doc-head"><div class="title-wrap"><h1><?php echo e($title); ?></h1><div class="title-rule"><span></span></div><div class="customer-name"><?php echo e($customer); ?></div><div class="city"><?php echo e($city ?: '-'); ?></div></div><div class="date-box"><div class="date-row"><b><?php echo e($docTypeLabel); ?> TARİHİ</b><strong><?php echo e(tr_date($offerDate)); ?></strong></div><div class="date-row"><b><?php echo e($docTypeLabel); ?> NO</b><strong><?php echo e($offerNo); ?></strong></div></div></div>
<table class="items"><thead><tr><th style="width:44%">ÜRÜN ADI</th><th style="width:14%"><?php echo e($quantityLabel); ?></th><th style="width:19%">BİRİM FİYATI</th><th style="width:23%">TUTAR</th></tr><tr class="sub"><th>ÜRÜN CİNSİ</th><th>MİKTAR</th><th>BİRİM FİYAT</th><th>TUTAR</th></tr></thead><tbody><?php foreach ($rows as $r): $qty=(float)($r['quantity'] ?? 0); $price=(float)($r['unit_price'] ?? 0); $line=(float)($r['line_total'] ?? 0); $has=!empty($r['product_name']) || !empty($r['product_type']) || $qty>0 || $price>0; ?><tr><td class="<?php echo $has ? '' : 'empty'; ?>"><?php echo e(($r['product_name'] ?? '') ?: ($r['product_type'] ?? '')); ?><?php echo (!empty($r['product_name']) && !empty($r['product_type'])) ? '<small>'.e($r['product_type']).'</small>' : ''; ?></td><td><?php echo $qty > 0 ? e(number_format($qty, 0, ',', '.')) : ''; ?></td><td><?php echo $price > 0 ? e(teklif_money($price)) : ''; ?></td><td class="right"><?php echo $line > 0 ? e(teklif_money($line)) : ''; ?></td></tr><?php endforeach; ?><tr class="total-line"><td colspan="2"></td><td class="label">ARA TOPLAM</td><td class="amount"><?php echo e(teklif_money($subtotal)); ?> <?php echo e($currency); ?></td></tr><?php if ($vatEnabled): ?><tr class="total-line"><td colspan="2"></td><td class="label">KDV (%<?php echo e((string)$vatRate); ?>)</td><td class="amount"><?php echo e(teklif_money($vatAmount)); ?> <?php echo e($currency); ?></td></tr><?php endif; ?><tr class="total-line"><td colspan="2"></td><td class="label">GENEL TOPLAM</td><td class="amount"><?php echo e(teklif_money($grandTotal)); ?> <?php echo e($currency); ?></td></tr></tbody></table>
<div class="note"><span class="note-mark">N</span><span>NOT</span><span class="note-text"><?php echo $note !== '' ? nl2br(e($note)) : ''; ?></span></div><?php if ($termText !== ''): ?><div class="term"><?php echo e($termText); ?></div><?php endif; ?></section>
<section class="bottom" data-footer="<?php echo e($footerText); ?>"><div class="features"><div class="feature"><div class="ficon">1</div><div><b>YÜKSEK KALİTE</b><span>Kaliteli üretim standardı</span></div></div><div class="feature"><div class="ficon">2</div><div><b>ZAMANINDA TESLİMAT</b><span>Siparişlerinizi zamanında teslim ediyoruz.</span></div></div><div class="feature"><div class="ficon">3</div><div><b>GÜVENİLİR HİZMET</b><span>Müşteri memnuniyetini önceliğimiz kabul ediyoruz.</span></div></div><div class="thanks">Teşekkür eder,<br>iyi çalışmalar dileriz.</div></div></section>
</main>
</body>
</html>
